project:
  type: website

website:
  title: "amos's blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Amos-li
      - icon: twitter
        href: https://twitter.com/underwing_lee
format:
  html:
    theme: cosmo
    css: styles.css



