project:
  type: website

website:
  title: "amos's blog"
  favicon: favicon_io/favicon.ico
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Amos-li
      - icon: twitter
        href: https://twitter.com/underwing_lee
  back-to-top-navigation: true
  google-analytics: G-NVFXJ5770C
format:
  html:
    theme: cosmo
    css: styles.css
comments:
  utterances:
    repo: Amos-li/amos-li.github.io



